function test_suite=test_meeg_chantype
    initTestSuite;

function test_meeg_chantype_

    props=get_senstype_properties();
    n=numel(props);
    for k=1:n
        prop=props{k};
        name=prop{1};
        nchan=prop{2};
        chan_labels=prop{3};
        chan_mapping=prop{4};

        sizes={'small','big'};
        for j=1:2
            size_=sizes{j};
            ds=cosmo_synthetic_dataset('type','meeg','sens',name,...
                                            'size',size_);
            nf=numel(ds.a.fdim.values{1});
            if strcmp(size_,'big')
                assertEqual(nf,nchan);
            end
            [tp,mp]=cosmo_meeg_chantype(ds);

            if ischar(chan_labels)
                assertEqual(unique(tp),{chan_labels})
            else
                chan_rep=repmat(chan_labels(:),...
                                ceil(nchan/numel(chan_labels)),1);
                assertEqual(tp,chan_rep(1:nf))
            end

            for m=1:numel(chan_mapping)
                cm=chan_mapping{m};
                assertEqual(mp.(cm{1}),cm{2});
            end


        end
    end

function props=get_senstype_properties()
    props={ {'neuromag306_all',306,...
                {'meg_axial', 'meg_planar', 'meg_planar'},...
                {{'meg_axial','neuromag306alt_mag'},...
                {'meg_planar','neuromag306alt_planar'}}},...
            {'neuromag306_planar',204,...
                'meg_planar',...
                {{'meg_planar','neuromag306alt_planar'}}},...
            {'neuromag306_planar_combined',102,...
                'meg_planar_combined',...
                {{'meg_planar_combined',...
                            'neuromag306alt_planar_combined'}}},...
            {'ctf151',151,...
                'meg_axial',...
                {{'meg_axial','ctf151'}}},...
            {'ctf151_planar',302,...
                'meg_planar',...
                {{'meg_planar','ctf151_planar'}}},...
            {'ctf151_planar_combined',151,...
                'meg_axial',...
                {{'meg_axial','ctf151'}}},...
            {'4d148',148,...
                'meg_axial',...
                {{'meg_axial','bti148'}}},...
            {'4d148_planar',296,...
                'meg_planar',...
                {{'meg_planar','bti148_planar'}}},...
            {'4d148_planar_combined',148,...
                'meg_axial',...
                {{'meg_axial','bti148'}}},...
            {'4d248',248,...
                'meg_axial',...
                {{'meg_axial','bti248'}}},...
            {'4d248_planar',496,...
                'meg_planar',...
                {{'meg_planar','bti248_planar'}}},...
            {'4d248_planar_combined',248,...
                'meg_axial',...
                {{'meg_axial','bti248'}}},...
            {'yokogawa64',64,...
                'meg_axial',...
                {{'meg_axial','yokogawa64'}}},...
            {'yokogawa64_planar',128,...
                'meg_planar',...
                {{'meg_planar','yokogawa64_planar'}}},...
            {'yokogawa64_planar_combined',64,...
                'meg_axial',...
                {{'meg_axial','yokogawa64'}}},...
            {'yokogawa64',64,...
                'meg_axial',...
                {{'meg_axial','yokogawa64'}}},...
            {'yokogawa64_planar',128,...
                'meg_planar',...
                {{'meg_planar','yokogawa64_planar'}}},...
            {'yokogawa64_planar_combined',64,...
                'meg_axial',...
                {{'meg_axial','yokogawa64'}}}};
        

        
        