function test_suite=test_meeg_find_layout()
    initTestSuite;
    
function test_meeg_find_layout_()
    props=get_props();
    n=numel(props);
    prev_name='';
    tic
    for k=1:n
        prop=props{k};
        
        name=prop{1};
        senstype=prop{2};
        lay_prop=prop{3};
        unsupp=prop{4};
        
        if ~strcmp(prev_name,name)
            ds=cosmo_synthetic_dataset('type','meeg','size','big',...
                                'sens',name,'ntargets',1,'nchunks',1);
        end
        
        lay=cosmo_meeg_find_layout(ds,'senstype',senstype);
        assertEqual(lay.name,lay_prop{1});
        
        nchans=lay_prop{2};
        assertEqual(size(lay.pos,1),nchans);
        
        chans=lay_prop{3};
        for j=1:numel(chans)
            if j==1
                cpos=1;
            elseif j==numel(chans)
                cpos=nchans;
            end
            if ~strcmp(chans{j},lay.label(cpos))
                cpos=strcmp(chans{j},lay.label,'exact');
                assert(numel(cpos)==1)
            end
            assertVectorsAlmostEqual(lay.pos(cpos,:),lay_prop{4}(j,:),...
                                'absolute',1e-4);
        end
                
        for j=1:numel(unsupp)
            assertExceptionThrown(@()cosmo_meeg_find_layout(ds,...
                            'senstype',unsupp{j}),'');
        end
        
        prev_name=name;
    end
    toc


function props=get_props()
    props={{'neuromag306_all','meg_planar',...
                    {'neuromag306all.lay',204,...
                            {'MEG0113', 'MEG2643'},...
                            [-73.4162 33.4167;61.2202 -20.3860]},...
                    {'eeg', 'meg_planar_combined'}},...
            {'neuromag306_all','meg_axial',...
                    {'neuromag306all.lay',102,...
                            {'MEG0111', 'MEG2641'},...
                            [-67.4162 35.9167;67.2202 -22.8860]},...
                    {'eeg', 'meg_planar_combined'}},...
            {'neuromag306_all','meg_combined_from_planar',...
                    {'neuromag306all.lay',204,...
                            {'MEG0113', 'MEG2643'},...
                            [-73.4162 33.4167;61.2202 -20.3860]},...
                    {'eeg', 'meg_planar_combined'}},...
            {'neuromag306_planar','meg_planar',...
                    {'neuromag306all.lay',204,...
                            {'MEG0113', 'MEG2643'},...
                            [-73.4162 33.4167;61.2202 -20.3860]},...
                    {'eeg', 'meg_axial', 'meg_planar_combined'}},...
            {'neuromag306_planar','meg_combined_from_planar',...
                    {'neuromag306all.lay',204,...
                            {'MEG0113', 'MEG2643'},...
                            [-73.4162 33.4167;61.2202 -20.3860]},...
                    {'eeg', 'meg_axial', 'meg_planar_combined'}},...
            {'neuromag306_planar_combined','meg_planar_combined',...
                    {'neuromag306cmb.lay',102,...
                            {'MEG0112+0113', 'MEG2642+2643'},...
                            [-67.4162 35.9167;67.2202 -22.8860]},...
                    {'eeg', 'meg_axial', 'meg_combined_from_planar',...
                                        'meg_planar'}},...
            {'ctf151','meg_axial',...
                    {'CTF151.lay',151,...
                            {'MLC11', 'MZP02'},...
                            [-0.4400 -4.0000;0.0000 -7.2900]},...
                    {'eeg', 'meg_combined_from_planar', 'meg_planar'}},...
            {'ctf151_planar','meg_planar',...
                    {'CTF151.lay',302,...
                            {'MLC11_dH', 'MZP02_dV'},...
                            [-0.4400 -4.0000;0.0000 -7.2900]},...
                    {'eeg', 'meg_axial', 'meg_planar_combined'}},...
            {'ctf151_planar','meg_combined_from_planar',...
                    {'CTF151.lay',302,...
                            {'MLC11_dH', 'MZP02_dV'},...
                            [-0.4400 -4.0000;0.0000 -7.2900]},...
                    {'eeg', 'meg_axial', 'meg_planar_combined'}},...
            {'ctf151_planar_combined','meg_planar_combined',...
                    {'CTF151.lay',151,...
                            {'MLC11', 'MZP02'},...
                            [-0.4400 -4.0000;0.0000 -7.2900]},...
                    {'eeg', 'meg_combined_from_planar',...
                                         'meg_planar'}},...
            {'4d148','meg_axial',...
                    {'4D148.lay',148,...
                            {'A1', 'A148'},...
                            [0.5000 0.5644;0.9055 0.8111]},...
                    {'eeg', 'meg_combined_from_planar', 'meg_planar'}},...
            {'4d148_planar','meg_planar',...
                    {'4D148.lay',296,...
                            {'A1_dH', 'A148_dV'},...
                            [0.5000 0.5644;0.9055 0.8111]},...
                    {'eeg', 'meg_axial', 'meg_planar_combined'}},...
            {'4d148_planar','meg_combined_from_planar',...
                    {'4D148.lay',296,...
                            {'A1_dH', 'A148_dV'},...
                            [0.5000 0.5644;0.9055 0.8111]},...
                    {'eeg', 'meg_axial', 'meg_planar_combined'}},...
            {'4d148_planar_combined','meg_planar_combined',...
                    {'4D148.lay',148,...
                            {'A1', 'A148'},...
                            [0.5000 0.5644;0.9055 0.8111]},...
                    {'eeg', 'meg_combined_from_planar',...
                                         'meg_planar'}},...
            {'4d248','meg_axial',...
                    {'4D248.lay',248,...
                            {'A1', 'A248'},...
                            [0.2306 -0.2606;34.3069 26.8896]},...
                    {'eeg', 'meg_combined_from_planar', 'meg_planar'}},...
            {'4d248_planar','meg_planar',...
                    {'4D248.lay',496,...
                            {'A1_dH', 'A248_dV'},...
                            [0.2306 -0.2606;34.3069 26.8896]},...
                    {'eeg', 'meg_axial', 'meg_planar_combined'}},...
            {'4d248_planar','meg_combined_from_planar',...
                    {'4D248.lay',496,...
                            {'A1_dH', 'A248_dV'},...
                            [0.2306 -0.2606;34.3069 26.8896]},...
                    {'eeg', 'meg_axial', 'meg_planar_combined'}},...
            {'4d248_planar_combined','meg_planar_combined',...
                    {'4D248.lay',248,...
                            {'A1', 'A248'},...
                            [0.2306 -0.2606;34.3069 26.8896]},...
                    {'eeg', 'meg_combined_from_planar',...
                                         'meg_planar'}},...
            {'eeg1020','',...
                    {'EEG1005.lay',21,...
                            {'Fp1', 'O2'},...
                            [-0.4853 1.4938;0.4854 -1.4939]},...
                    {'meg_axial', 'meg_combined_from_planar',...
                                         'meg_planar', ...
                                         'meg_planar_combined'}},...
            {'eeg1010','',...
                    {'EEG1005.lay',86,...
                            {'Fp1', 'I2'},...
                            [-0.4853 1.4938;0.6066 -1.8672]},...
                    {'meg_axial', 'meg_combined_from_planar',...
                                         'meg_planar', ...
                                         'meg_planar_combined'}},...
            {'eeg1005','',...
                    {'EEG1005.lay',335,...
                            {'Fp1', 'OI2'},...
                            [-0.4853 1.4938;0.5461 -1.6806]},...
                    {'meg_axial', 'meg_combined_from_planar',...
                                         'meg_planar', ...
                                         'meg_planar_combined'}},...
    };


